name: Bug Report
description: Something not working as expected
body:
  - type: textarea
    attributes:
      label: Current behavior
      description: Describe how the issue manifests.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: Describe what the desired behavior would be.
    validations:
      required: true

  - type: input
    attributes:
      label: "`codemash` version"
      description: Version set in `package.json` `dependencies`.
    validations:
      required: true

  - type: textarea
    attributes:
      label: "`codemash` configuration"
      description: Link to your repository or relevant part of the `codemash` config.
    validations:
      required: false

